How 147
wolfbeacon/howlplay-front-end pull request #33
Opened 2018-06-24 19:38 UTC by fpunny

- Displayscore title changes according to screen (Not stuck on Top 10)
- Display actual answer rather than answer 1...n (With exception to images obviously)
- Going to dashboard/displayscore without logging in first would throw you back to the login page

2018-06-25 00:03 UTC, bradyvall requested changes
I believe this needs changes Nafees suggested in Slack with **Image** becoming **IMG** although I may be mistaken, for the **INP** I will create a ticket.

2018-06-28 04:42 UTC, fpunny commented
@bradyvall Good to merge?

2018-06-28 22:03 UTC, bradyvall commented
Approved

2018-06-28 22:04 UTC, bradyvall approved these changes

2018-06-30 03:07 UTC, merged